### ISSUE TITLE
Feature request: Add input for microk8s dockerhub mirror configuration

### ISSUE THREAD

**Issue by yhaliaw** [charmed-kubernetes/actions-operator#62]
When running many self-hosted runners on a server, installing microk8s can hit the [rate-limit on Dockerhub](https://docs.docker.com/docker-hub/download-rate-limit/) for an account, as microk8s will be downloading images during installation.

One method to bypass this is with [a private docker registry that acts as a dockerhub mirror](https://docs.docker.com/docker-hub/mirror/)

The microk8s allows for using private docker registry as dockerhub mirror:

https://microk8s.io/docs/dockerhub-limits#h-3-use-a-private-image-registry-to-mirror-dockerhub-5

This setting will need to be setup after the installation of microk8s.

This feature request propose a input option for the workflow that takes the URL of dockerhub mirror. The workflow would then setup microk8s according to the link above after installation.

**Comment by yhaliaw** [comment]
I have forked this repo and add a branch for a drafted version of the changes:
https://github.com/yhaliaw/actions-operator/tree/microk8s-docker-registry

**Comment by yhaliaw** [comment]
I have put together a PR for this: https://github.com/charmed-kubernetes/actions-operator/pull/63

**Comment by addyess** [comment]
with #63 merged, this issue is now closed
