### ISSUE TITLE
The `latest/stable` channel for juju has been removed from the snap store

### ISSUE THREAD

**Issue by weiiwang01** [charmed-kubernetes/actions-operator#72]
The default channel for juju in the snap store has now been changed to `3/stable` and channel `latest/stable` has been removed. 

While it is possible to update the default `juju-channel` option to `3/stable`, but that the previous `latest/stable` channel was pointed with juju 2. This means workflows that relied on the default setting will be upgraded to juju 3.

https://github.com/charmed-kubernetes/actions-operator/blob/c056d0cc4a9ff613937b8329c4883bc86c6049f5/action.yaml#L39-L42

**Comment by addyess** [comment]
I think upgrading to `3/stable` is the right call
